### ISSUE TITLE
UpdateLastColumn fails when opening file from vim-dirvish

### ISSUE THREAD

**Issue by jparise** [qpkorr/vim-bufkill#12]
When I open a file from a [vim-dirvish](https://github.com/justinmk/vim-dirvish) buffer, vim-bufkill prints this error:

```
UpdateLastColumn failed to find bufnr 5 in w:BufKillList
```

I'm not sure if that's causing any real problems; I'm a relatively new vim-bufkill user and don't use many of its features yet.

I'm using vim 8.0 and the current HEAD versions of both plugins. I can also reproduce this on vim 7.4.

**Comment by qpkorr** [comment]
Thanks for the report.  Someone else reported seeing problems with netrw, so there might well be an issue, perhaps that some vim function providing information about a file doesn't work the same way when the file is opened remotely.  I don't have a lot of time to dig into such issues at present - and if they're not causing real problems, perhaps the need is small anyway.  Maybe let me know when/if you work out what the real problems are?  Thanks, John

**Comment by qrevel** [comment]
I have this problem with netrw too

**Comment by linosgian** [comment]
Same issue with NERDTree when I open a folder with it and then try to jump over to NERDTree's split

**Comment by tony** [comment]
I have this issue with fzf, when trying to do a ctrl-v (vsplit) to open a file.

```
"filename.js" 459L, 12110C
UpdateLastColumn failed to find bufnr 2 in w:BufKillList
UpdateLastColumn failed to find bufnr 2 in w:BufKillList
Error detected while processing function fzf#run[69]..<SNR>113_callback:
line   33:
Vim(py3file):Traceback (most recent call last):
Press ENTER or type command to continue
```

Going to give this a try: https://github.com/moll/vim-bbye (nevermind, license is AGPL!)

**Comment by qpkorr** [comment]
@tony thanks for the tip re bbye - if it restores buffers in a sensible order (like emacs does, and bufkill tried to emulate) then it might well be a better (newer, cleaner, more actively updated) option!

**Comment by jparise** [comment]
#20 solved this issue for me. Thanks @qpkorr and @mortonfox!
