### ISSUE TITLE
Is it :BD or <Leader>bd?

### ISSUE THREAD

**Issue by MightyCreak** [qpkorr/vim-bufkill#14]
Hi!

Thanks for this plugin, it's very useful!

The main page says that there are a bunch of shortcuts already defined like `:BD`, `:BB`, `:BF`, ...
But I discovered that the same shortcuts were also defined, but with `<Leader>`: `<Leader>bd`, `<Leader>bb`, `<Leader>bf`, ...

I've try to read bufkill.vim and understand which was which, but I couldn't see where the `:` shortcuts were defined. I've only saw the `<Leader>` ones starting at line 224.

It would be nice if either one way was chosen or if the doc was explicitly saying that both are defined by default.

(the root of my problem was that it was creating conflicts with LeaderF)

**Comment by adambyrtek** [comment]
You can avoid creating the leader mappings with the following option:
```
let g:BufKillCreateMappings = 0
```

**Comment by MightyCreak** [comment]
Thx!

I think this has its place in the README.md

**Comment by ladislas** [comment]
yup took me a while to figure out :) even though I love the leader mappings!
