### ISSUE TITLE
error using neovim and vim plug

### ISSUE THREAD

**Issue by ladislas** [qpkorr/vim-bufkill#16]
Hi there! 

I just updated vim plug and when launching neovim, I get the following error:

```
[vim-plug] Invalid argument: bufkill.vim (implicit `vim-scripts' expansion is deprecated)
Press ENTER or type command to continue
```

Is this that can be fixed easily?
Do you think I should also open an issue with vim plug?

**Comment by ladislas** [comment]
my bad, I found the solution, I need to use `qpkorr/vim-bufkill`

thanks for the good work :)

**Comment by qpkorr** [comment]
Good work yourself! :)  I was drawing total blanks about the "vim-scripts expansion" business, glad you could sort it! (and glad you find it useful)

**Comment by ladislas** [comment]
to be more precise, you need to put in your .vimrc the following:

```vimscript
Plug 'qpkorr/vim-bufkill'
```
