### ISSUE TITLE
Which theme and font?

### ISSUE THREAD

**Issue by jesseleite** [qpkorr/vim-bufkill#19]
Which theme and font are you using in the readme gif?  😅

![](https://cloud.githubusercontent.com/assets/9512444/10005557/c1c41cc0-60af-11e5-85cc-39503efc7cad.gif)

**Comment by qpkorr** [comment]
I wrote the plugin, but https://github.com/olimorris felt the readme could be better, and made the great gif.  Hopefully he can help!

**Comment by qpkorr** [comment]
If it's too hard to contact him through there (I see his website doesn't work) try here: https://github.com/qpkorr/vim-bufkill/pull/3

**Comment by jesseleite** [comment]
Cool, closing this, and will continue in #3, thanks 👍
