### ISSUE TITLE
Poor readme

### ISSUE THREAD

**Issue by olimorris** [qpkorr/vim-bufkill#2]
I just want to say what an awesome plugin this is. I too was hugely annoyed that VIM did not have this feature built in...you open a split, load it full of files and want to clear some without losing your split. This plugin does it to perfection.

However your readme does not do the plugin justice. It took me a good 5 minutes  (okay it is 1:00am UK time and I'm tired) to workout that I should use `:BD`. I was doing `:BUN/:BD`. You could give the readme some explicit examples to show just how fantastic this is and I think a bloody good animated GIF wouldn't go a miss either.

Other than that. Top marks!

**Comment by qpkorr** [comment]
Hi @olimorris - thanks for your praise - ha - and perhaps more for your validation that I wasn't crazy in being highly frustrated by the default vim behaviour! :)  (especially when emacs seemed to get it just right! ;)

Thanks also for the feedback on the readme - makes sense/sounds reasonable.  Perhaps the best I can do it write down how I use the plugin myself, in case that helps.  If you'd then like to comment on that with your own experiences, I'd appreciate getting 100% more information! 

Glad it's helping you enjoy vim!

**Comment by olimorris** [comment]
Absolutely. Happy to contribute how I use it too.

**Comment by qpkorr** [comment]
Thanks Oli.  By the way, when I went to edit the readme file, I thought it was better in text form than it comes up on the github page.  Not sure how it will come up in email, but I'll try posting it in here...

When you want to unload/delete/wipe a buffer, use:
  :bun/:bd/:bw to close the window as well (vim command), or
  :BUN/:BD/:BW to leave the window intact (this script).

To move backwards/forwards through recently accessed buffers, use:
  :BB/:BF

To move to the alternate buffer whilst preserving cursor column, use:
  :BA

To my brain... that seems kind of reasonable.... not to yours though?

**Comment by olimorris** [comment]
I think the big selling point with your plugin is how similarly it maps to standard Vim commands however because the readme was so text heavy I just didn't see the relationship between `:BD` and `:bd`. My bad perhaps but thought it could have been structured to be a bit more of a 'punchy' read.

I've submitted a pull request #3 so let me know what you think, and feel free to ignore it if you don't like :)

**Comment by qpkorr** [comment]
Um, wow?  Awesome stuff Oli, thank you.  Well - I say thank you though really I'd be trying to say thanks in advance from any other people who might benefit from the script thanks to your great sales job.  I've had a quick look and it looks excellent - I'll investigate in more detail this weekend and get it updated.  Great stuff!

**Comment by olimorris** [comment]
Not a problem. Thanks to you for such a great plugin!

**Comment by qpkorr** [comment]
Hmm - seems the animated gifs aren't working fully - do you suggest I add those gifs to my repo, or continue to try to source them from tinypic?

**Comment by olimorris** [comment]
I think adding them to your repo and letting Github serve them would be more optimal. Infact I could re do those videos to increase the FPS as they're bit jumpy.

**Comment by qpkorr** [comment]
Sounds good to me Oli - let me know if I need to do more than just accepting a pull request.  Thanks!
John

**Comment by olimorris** [comment]
I've re done them #5 . Much better!

**Comment by qpkorr** [comment]
Thanks Oli - looks great (and is working fine, unlike when sourcing form tinypic).  Thanks again!

**Comment by olimorris** [comment]
Glad I could help.
