### ISSUE TITLE
Error when deleting Fugitive buffers

### ISSUE THREAD

**Issue by jandamm** [qpkorr/vim-bufkill#28]
When executing `BD` in a fugitive buffer (`Gstatus`), the buffer is removed and the window is preserved but this message is presented:
```
Error detected while processing function <SNR>64_BufKill:
line 140:
E516: No buffers were deleted: bd53
```

I've tried to add detection for `&bufhidden=delete` but before executing the kill command `&bufhidden` is ``.

Maybe just silencing `E516` would be sufficient?

**Comment by qpkorr** [comment]
Hi - Thanks for the report and request - I might do a little more digging over coming days to see if there's any more appropriate solutions.

**Comment by znculee** [comment]
Thank you for your contribution. https://github.com/qpkorr/vim-bufkill/pull/29 Here's my workaround before your code is pulled. https://github.com/qpkorr/vim-bufkill/issues/21#issuecomment-722750195

**Comment by tillydray** [comment]
I'm experiencing this same issue, my vimrc is well-modified but it's interesting to know it's also happening with a nearly plain vimrc. I should specify, it seems to work, but it throws an error
