### ISSUE TITLE
Getting rid of error and 'press ENTER to continue'?

### ISSUE THREAD

**Issue by louwers** [qpkorr/vim-bufkill#8]
Just a suggestion: `:bd` shows a warning message when trying to delete a buffer that has been modified. `:BD`, on the other hand, shows an error ("Error detected while processing function <SNR>18_BufKill:") and that same warning message. It also shows 'Press ENTER to continue'. 

I looked into it a little, and I think we can replicate `:bd`'s behavior with:

``` vim
echohl ErrorMsg
echo "No write since last change for buffer '" . bufname(s:BufKillBufferToKill) . "' (add ! to override)"
echohl None
```

**Comment by qpkorr** [comment]
Hi! Better late than never - thanks, good idea.  I usually have 'confirm' enabled so I never see this message, but your suggestion does make sense, and I'll upload a new version including it soon (testing at present).
Cheers, John
